### ISSUE TITLE
Fortnite 3.5 Crashing!

### ISSUE THREAD

**Issue by yoyosingh123** [RealProHenis/ButterflyLauncher_V1#6]
Hey

So I've tested Fortnite 3.5 version and It's crashing most likely because of the dll file that launcher injects could you please let us choose it manually instead of automatically injecting. 

Also please open source this project I would love to learn from this I absolutely love your program. 

Thanks!

**Comment by RealProHenis** [comment]
Hey yoyosingh123, just released update v1.0.2.7 that fixes crashing on older versions of Fortnite. (use the checkbox above the Play button before launching)
